### ISSUE TITLE
Document markdown usage

### ISSUE THREAD

**Issue by WillMoggridge** [canonical-websites/tutorials.ubuntu.com#196]
Document markdown usage for adding and testing, to allow people to write and contribute tutorials

**Comment by didrocks** [comment]
There are actually guidelines in a branch, but it's first waiting on the previous branch I did a PR for a week ago. Mind getting this one reviewed and then, I can tag a release and push the guidelines ?

**Comment by WillMoggridge** [comment]
Oh sure, I was just noting an issue to remind me for Friday but that sounds good!
I imagine I may want to improve on the contributing guidelines and alike along with that.

**Comment by didrocks** [comment]
Sure! FYI, the guidelines can refer to the example file once https://github.com/canonical-websites/tutorials.ubuntu.com/pull/197 is in, which has the tone and other similar illustrations.

Then, it can say that tutorials should be in `tutorials` directory (I suggest one per folder, so that images asset are in).
Some instructions are in https://github.com/ubuntu/tutorial-deployment/ if you want to get inspiration from. Basically, it's `bin/serve [path to one or more tutorials you want to iterate on]'

**Comment by WillMoggridge** [comment]
This is in a better position now, so I will close this
