### ISSUE TITLE
Review - Basic snap usage

### ISSUE THREAD

**Issue by evilnick** [canonical-websites/tutorials.ubuntu.com#273]
The new markdown version of this tutorial needs to be reviewed for style and content

**Comment by leecolleton** [comment]
The tutorial instructs the installation of the **hello** snap in [step 3](https://tutorials.ubuntu.com/tutorial/basic-snap-usage#2) and the removal of the **hello-world** snap in [step 4](https://tutorials.ubuntu.com/tutorial/basic-snap-usage#3), which will lead to confusion by novice users.

Also, the introduction could use a more thorough explanation of why someone would want to use the snap utility instead of a traditional package manager. This is explained further on in the tutorial, but ought to be included in the intro to engage the audience.
