### ISSUE TITLE
I want to create a bootable USB, but I seem to be sent to [Upgrade Ubuntu desktop] 

### ISSUE THREAD

**Issue by SaltyDave** [canonical-websites/tutorials.ubuntu.com#771]
<describe the issue> I am trying to create a bootable USB to use on an 64bit Windows 10 Dell, PC. I do not want to upgrade. I want to download a 64 bit version. I am on a very VERY slow, and unreliable Internet connection.

I was following the instructions at https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#1   However, the links there seem to send me to an 'upgrade your existing Ububtu' page, not a download a new install ISO. 

Many thanks for all of the work that you all do. This is confusing enough when the Instructions are clear.

**Comment by evilnick** [comment]
Hi, the link points to the main download page, as there are various different flavours you may be interested in etc. If you click on the large 'Ubuntu Desktop' heading rather than the upgrade link underneath it, you will get to this page: https://www.ubuntu.com/download/desktop. Sorry this wasn't more obvious
