### ISSUE TITLE
spelling mistake 

### ISSUE THREAD

**Issue by NixonNelson** [canonical-websites/tutorials.ubuntu.com#776]
![sketch](https://user-images.githubusercontent.com/40900101/42396666-4d4cb8f8-8180-11e8-84e7-18391daa8e8b.png)
the SHA256SUMS should be SHA256SUMS.txt 
I tried the later which gave me error.
Thank you .

**Comment by evilnick** [comment]
If you check on the server, you will see that the file is actually called SHA256SUMS. On Windows, because it doesn't like 'typeless' files, you will often find it renames the file with a suffix (in this case .txt)
So it isn't a mistake, but probably worth making a note for Windows users. thanks for pointing it out
