### ISSUE TITLE
[Create a bootable USB stick on Windows] Etcher instead of Rufus?

### ISSUE THREAD

**Issue by Ads20000** [canonical-websites/tutorials.ubuntu.com#895]
Would it be simpler if [this tutorial](https://tutorials.ubuntu.com/tutorial/tutorial-create-a-usb-stick-on-windows#1) used [Etcher](https://www.balena.io/etcher/) rather than Rufus? Etcher is also free and open-source software but the UI seems much cleaner so having that in the tutorial rather than Rufus might make installing Ubuntu easier for people? Etcher is based on Electron, so there may be performance impacts with using it over Rufus, but the apparent ease of use seems worth considering.

This is very subjective and can be closed if people disagree but I thought it should be worth considering to make the tutorial less 'scary-looking'.

**Comment by fitojb** [comment]
I wouldn’t support it, because Etcher:
* Is a web application that uses Electron, so its performance is much worse
* Makes a [number of shady connections to data collectors and analytics sites](https://forums.balena.io/t/serious-privacy-concerns-with-etcher-1-4-4/4103), incl. Facebook and Google, to try to track usage and invade my privacy, *even when set not to do so* (!)

**Comment by Ads20000** [comment]
It is, I suppose, a case of ease-of-install _versus_ performance.
On the second point, fair enough, I suppose that I should wait for that issue to be (properly) resolved before advocating the change.
